// const products = [
//     {
//         _id: '1',
//         name: 'bluetooth',
//         image: '/images/image1.jpg',
//         description: 'Bluetooth technology is wonderful,Bluetooth technology is wonderful,Bluetooth technology is wonderful',
//         brand: 'Apple',
//         category: 'Electronics',
//         price: 100,
//         countInStock: 3,
//         ratings: 4.5,
//         numReviews: 4,
//     },
//     {
//         _id: '2',
//         name: 'wifi',
//         image: '/images/image2.jpg',
//         description: 'Wifi technology is wonderful,Bluetooth technology is wonderful,Bluetooth technology is wonderful',
//         brand: 'Samsung',
//         category: 'Electronics',
//         price: 120,
//         countInStock: 2,
//         ratings: 4,
//         numReviews: 3,
//     },
//     {
//         _id: '3',
//         name: 'infared',
//         image: '/images/image3.jpg',
//         description: 'Infared technology is wonderful,Bluetooth technology is wonderful,Bluetooth technology is wonderful',
//         brand: 'Nokia',
//         category: 'Electronics',
//         price: 80,
//         countInStock: 9,
//         ratings: 1,
//         numReviews: 9,
//     },
//     {
//         _id: '4',
//         name: 'blueray',
//         image: '/images/image4.jpg',
//         description: 'BlueRay technology is wonderful,Bluetooth technology is wonderful,Bluetooth technology is wonderful',
//         brand: 'Apple',
//         category: 'Electronics',
//         price: 40,
//         countInStock: 6,
//         ratings: 5,
//         numReviews: 2,
//     },


//     {
//         _id: '5',
//         name: 'wifi',
//         image: '/images/image5.jpg',
//         description: 'Wifi technology is wonderful,Bluetooth technology is wonderful,Bluetooth technology is wonderful',
//         brand: 'Samsung',
//         category: 'Electronics',
//         price: 120,
//         countInStock: 2,
//         ratings: 4,
//         numReviews: 3,
//     },


//     {
//         _id: '6',
//         name: 'blueray',
//         image: '/images/image6.jpg',
//         description: 'BlueRay technology is wonderful,Bluetooth technology is wonderful,Bluetooth technology is wonderful',
//         brand: 'Apple',
//         category: 'Electronics',
//         price: 40,
//         countInStock: 6,
//         ratings: 5,
//         numReviews:2,
//     },

//     {
//         _id: '7',
//         name: 'wifi',
//         image: '/images/image7.jpg',
//         description: 'Wifi technology is wonderful,Bluetooth technology is wonderful,Bluetooth technology is wonderful',
//         brand: 'Samsung',
//         category: 'Electronics',
//         price: 120,
//         countInStock: 2,
//         ratings: 4,
//         numReviews: 3,
//     },
//     {
//         _id: '8',
//         name: 'wifi',
//         image: '/images/image8.jpg',
//         description: 'Wifi technology is wonderful,Bluetooth technology is wonderful,Bluetooth technology is wonderful',
//         brand: 'Samsung',
//         category: 'Electronics',
//         price: 120,
//         countInStock: 2,
//         ratings: 4,
//         numReviews: 3,
//     },
    
// ]

// export default products;